/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/health': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations['HealthHealth'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/otel/ingest/v1/traces': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OtelIngestSpans */
        post: operations['OtelIngestV1TracesOtelIngestSpans'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/metrics': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations['MetricsMetrics'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/session/register': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** SessionRegister */
        post: operations['SessionRegisterSessionRegister'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/sandbox_logs': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SandboxLogs */
        get: operations['SandboxLogsSandboxLogs'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/logs': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logs */
        get: operations['LogsLogs'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/logs/{uid}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LogsByUid */
        get: operations['LogsUidLogsByUid'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/logs/{uid}/{iid}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LogsByUidAndIid */
        get: operations['LogsUidIidLogsByUidAndIid'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/echo/{uid}/{iid}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Echo */
        get: operations['EchoUidIidEcho'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/echo/{uid}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** EchoAll */
        get: operations['EchoUidEchoAll'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/echo': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** EchoGlobal */
        get: operations['EchoEchoGlobal'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/agent/create': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AgentCreate */
        post: operations['AgentCreateAgentCreate'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/agent/destroy/{uid}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** AgentDestroy */
        delete: operations['AgentDestroyUidAgentDestroy'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/schema/multiplex-messages': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** MultiplexMessageSchemaDocs */
        get: operations['SchemaMultiplexMessagesMultiplexMessageSchemaDocs'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/traces': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Traces */
        get: operations['TracesTraces'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/traces/{trace_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GetTrace */
        get: operations['TracesTraceIdGetTrace'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/traces/detailed': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GetDetailedTraces */
        get: operations['TracesDetailedGetDetailedTraces'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/traces/stream': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** StreamTraces */
        get: operations['TracesStreamStreamTraces'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/traces/stream/{trace_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** StreamTraceUpdates */
        get: operations['TracesStreamTraceIdStreamTraceUpdates'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateAgentRequest */
        CreateAgentRequest: {
            doc?: string | null;
            system?: string | components['schemas']['PromptTemplate'] | null;
            model: string;
            json: boolean;
            streaming: boolean;
            /** Format: binary */
            warp_globals_payload: string;
            /** @default python/v0 */
            protocol: string;
            max_tokens_per_invocation?: number | null;
            max_tokens_per_round?: number | null;
            max_rounds?: number | null;
            reasoning_effort?: ('none' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh') | null;
        };
        /** MultiplexCancelMessage */
        MultiplexCancelMessage: {
            uid: string;
            iid: string;
            timestamp?: string;
            /** @constant */
            type: 'cancel';
        };
        /** MultiplexDataMessage */
        MultiplexDataMessage: {
            uid: string;
            iid: string;
            /** Format: binary */
            data: string;
            timestamp?: string;
            /** @constant */
            type: 'data';
        };
        /** MultiplexErrorMessage */
        MultiplexErrorMessage: {
            iid: string;
            error_name: string;
            error_message?: string | null;
            timestamp?: string;
            uid?: string | null;
            session_id?: string | null;
            session_manager_id?: string | null;
            /** @constant */
            type: 'error';
        };
        /** MultiplexInvocationEventMessage */
        MultiplexInvocationEventMessage: {
            uid: string;
            iid: string;
            /** @enum {string} */
            event: 'ENTER' | 'EXIT' | 'ERROR';
            timestamp?: string;
            /** @constant */
            type: 'invocation';
        };
        /** MultiplexInvokeMessage */
        MultiplexInvokeMessage: {
            match_id: string;
            uid: string;
            /** Format: binary */
            warp_locals_payload: string;
            streaming: boolean;
            parent_uid?: string | null;
            parent_iid?: string | null;
            prompt?: string | components['schemas']['PromptTemplate'] | null;
            timestamp?: string;
            /** @constant */
            type: 'invoke';
        };
        /** MultiplexNewIIDResponse */
        MultiplexNewIIDResponse: {
            uid: string;
            iid: string;
            match_id: string;
            timestamp?: string;
            /** @constant */
            type: 'new_iid';
        };
        /** MultiplexTypes */
        MultiplexTypes: {
            MultiplexMessage:
                | components['schemas']['MultiplexDataMessage']
                | components['schemas']['MultiplexErrorMessage']
                | components['schemas']['MultiplexInvocationEventMessage']
                | components['schemas']['MultiplexNewIIDResponse']
                | components['schemas']['MultiplexCancelMessage']
                | components['schemas']['MultiplexInvokeMessage'];
            MultiplexClientMessage:
                | components['schemas']['MultiplexInvokeMessage']
                | components['schemas']['MultiplexDataMessage']
                | components['schemas']['MultiplexCancelMessage'];
            MultiplexClientInstanceMessage:
                | components['schemas']['MultiplexDataMessage']
                | components['schemas']['MultiplexCancelMessage'];
            MultiplexServerMessage:
                | components['schemas']['MultiplexNewIIDResponse']
                | components['schemas']['MultiplexErrorMessage']
                | components['schemas']['MultiplexDataMessage']
                | components['schemas']['MultiplexInvocationEventMessage'];
            MultiplexServerInstanceMessage:
                | components['schemas']['MultiplexErrorMessage']
                | components['schemas']['MultiplexDataMessage']
                | components['schemas']['MultiplexInvocationEventMessage'];
        };
        /** PromptTemplate */
        PromptTemplate: {
            template: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        [key: string]: string | number;
                    };
                };
            };
        };
    };
    OtelIngestV1TracesOtelIngestSpans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    MetricsMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
        };
    };
    SessionRegisterSessionRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    SandboxLogsSandboxLogs: {
        parameters: {
            query?: {
                fmt?: 'zip' | 'html' | 'log';
                max_files?: number;
                max_chunks?: number;
                find?: string;
                uid?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
    LogsLogs: {
        parameters: {
            query?: {
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
    LogsUidLogsByUid: {
        parameters: {
            query?: {
                type?: string | null;
            };
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
    LogsUidIidLogsByUidAndIid: {
        parameters: {
            query?: {
                type?: string | null;
            };
            header?: never;
            path: {
                uid: string;
                iid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
    EchoUidIidEcho: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
                iid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
    EchoUidEchoAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
    EchoEchoGlobal: {
        parameters: {
            query: {
                uid: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
    AgentCreateAgentCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['CreateAgentRequest'];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': string | unknown;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
    AgentDestroyUidAgentDestroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
    SchemaMultiplexMessagesMultiplexMessageSchemaDocs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['MultiplexTypes'];
                };
            };
        };
    };
    TracesTraces: {
        parameters: {
            query?: {
                start?: number | null;
                end?: number | null;
                limit?: number;
                service?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
    TracesTraceIdGetTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
    TracesDetailedGetDetailedTraces: {
        parameters: {
            query?: {
                start?: number | null;
                end?: number | null;
                limit?: number;
                service?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
    TracesStreamStreamTraces: {
        parameters: {
            query?: {
                service?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
    TracesStreamTraceIdStreamTraceUpdates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        status_code: number;
                        detail: string;
                        extra?:
                            | null
                            | {
                                  [key: string]: unknown;
                              }
                            | unknown[];
                    };
                };
            };
        };
    };
}
